# https://cloud.google.com/cloud-build/docs/speeding-up-builds
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _PROJECT: cli
  _IMAGE: 'genesis'
  _BINARIES_BUCKET : 'infra-dev-binaries'
timeout: '15m'
steps:
  - id: 'mkdir'
    name: 'ubuntu'
    args: ['mkdir', './bin']
    waitFor:
      - '-'
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_IMAGE:$BRANCH_NAME',
      '--cache-from', '$_IMAGE:$BRANCH_NAME',
      '.',
      '-f','binaries.Dockerfile'
    ]
    waitFor:
      - 'mkdir'
  # create container based off image (but don't run)
  - id: createContainer
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '--name', 'output', '$_IMAGE:$BRANCH_NAME' ]
    waitFor:
      - 'build'

  - id: copyBin
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'cp', 'output:/opt/genesis', './bin/' ]
    waitFor:
      - 'createContainer'
  # copy binary to public bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'cp', '-r', './bin/', 'gs://$_BINARIES_BUCKET/cli/' ]
    waitFor:
      - 'copyBin'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'installer.sh', 'gs://$_BINARIES_BUCKET/cli/install.sh' ]
    waitFor:
      - 'copyBin'

options:
  machineType: 'N1_HIGHCPU_32'