# https://cloud.google.com/cloud-build/docs/speeding-up-builds
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _PROJECT: cli
  _IMAGE: 'genesis'
  _BINARIES_BUCKET : 'assets.whiteblock.io'
  _VERSION_FILE: '.version'
timeout: '15m'
steps:
  - id: 'mkdir'
    name: 'ubuntu'
    args: ['mkdir', './bin']
    waitFor:
      - '-'
  - id: 'version'
    name: 'ubuntu'
    args: ['bash','-c',"echo -n $SHORT_SHA > $_VERSION_FILE"]
    waitFor:
      - '-'
  - id: builder
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'builder:$_IMAGE-$BRANCH_NAME',
      '.',
      '-f','binaries.Dockerfile'
    ]
    waitFor:
      - 'mkdir'
      - 'version'

  - id: build
    name: 'builder:$_IMAGE-$BRANCH_NAME'
    env:
      - 'OUTPUT_DIR=./bin'
      - 'SHORT_SHA=$SHORT_SHA'
    args: [
      'make ',
      '-e',
      "multiplatform"
    ]
    waitFor:
      - 'builder'

  # copy binary to public bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ '-m', 'cp', '-r', './bin/', 'gs://$_BINARIES_BUCKET/cli/' ]
    waitFor:
      - 'build'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'installer.sh', 'gs://$_BINARIES_BUCKET/cli/install.sh' ]
    waitFor:
      - 'build'
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', '$_VERSION_FILE', 'gs://$_BINARIES_BUCKET/cli/latest' ]
    waitFor:
      - 'build'

options:
  machineType: 'N1_HIGHCPU_32'